// generated by gen/fig_ch09.py — predicted probabilities of the chapter 9 prediction model (2,400 patients)
window.EXTRA_WIDGETS["ch09_thr"] = function (el, H) {
  const C1 = [0, 0, 0, 0, 0, 0, 3, 5, 11, 9, 14, 5, 10, 16, 18, 21, 16, 23, 14, 14, 14, 10, 11, 20, 8, 13, 15, 15, 11, 11, 12, 12, 9, 6, 12, 5, 15, 9, 8, 8, 6, 8, 6, 9, 7, 7, 9, 7, 5, 4, 5, 6, 5, 3, 3, 5, 3, 3, 1, 0, 3, 5, 0, 1, 2, 2, 3, 3, 2, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], C0 = [0, 0, 0, 0, 0, 0, 32, 59, 88, 91, 100, 108, 96, 83, 75, 103, 113, 68, 80, 68, 56, 49, 43, 43, 41, 43, 39, 27, 26, 25, 26, 22, 24, 22, 15, 17, 24, 11, 16, 8, 8, 17, 8, 10, 10, 10, 5, 8, 3, 1, 6, 2, 2, 3, 1, 4, 3, 5, 1, 4, 4, 2, 1, 1, 1, 1, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];          // patients per 0.01-wide bin of predicted risk (hospitalized / not)
  const N1 = C1.reduce((a, b) => a + b, 0), N0 = C0.reduce((a, b) => a + b, 0);
  const PREV0 = N1 / (N1 + N0), AUC = 0.6975;
  let thr = 20, prev = "cohort";
  const f1 = v => (Math.round(v * 1000 + 1e-7) / 10).toFixed(1) + "%";
  const n0 = v => Math.round(v).toLocaleString("en-US");
  el.innerHTML = `<p class="wt">직접 바꿔 보기 <span class="pill">계산기</span></p>
    <p class="wd">본문 예측모형의 예측확률(환자 2,400명)입니다. 임계값을 옮기면 "고위험"으로 분류되는 환자가 바뀌어 민감도·특이도·정확도가 달라집니다. 사건 비율을 바꾸면 같은 모형(같은 C 통계량)이라도 양성예측도와 정확도가 어떻게 변하는지 볼 수 있습니다.</p>
    <div class="wrow"><label for="c9thr">임계값 <b id="c9thrv"></b></label>
      <input type="range" id="c9thr" min="5" max="60" step="1" value="20" style="flex:1;min-width:180px"></div>
    <div class="wrow"><span>1년 입원 비율</span><div class="seg" role="group" aria-label="사건 비율">
      <button type="button" data-p="cohort" aria-pressed="true">이 코호트 (${f1(PREV0)})</button>
      <button type="button" data-p="0.05" aria-pressed="false">5%</button>
      <button type="button" data-p="0.5" aria-pressed="false">50%</button></div></div>
    <div class="wchart" id="c9chart"></div>
    <div class="stats">
      <div class="stat"><div class="sl">민감도</div><div class="sv" id="c9se"></div></div>
      <div class="stat"><div class="sl">특이도</div><div class="sv" id="c9sp"></div></div>
      <div class="stat"><div class="sl">양성예측도</div><div class="sv" id="c9ppv"></div></div>
      <div class="stat"><div class="sl">음성예측도</div><div class="sv" id="c9npv"></div></div>
      <div class="stat"><div class="sl">정확도</div><div class="sv" id="c9acc"></div></div>
      <div class="stat"><div class="sl">전원 "입원 안 함" 예측의 정확도</div><div class="sv" id="c9none"></div></div>
      <div class="stat"><div class="sl">C 통계량 (임계값과 무관)</div><div class="sv">${AUC.toFixed(2)}</div></div>
    </div>
    <p class="wd" id="c9note" style="margin-top:10px"></p>`;
  function draw() {
    const TP = C1.slice(thr).reduce((a, b) => a + b, 0), FP = C0.slice(thr).reduce((a, b) => a + b, 0);
    const se = TP / N1, sp = 1 - FP / N0;
    const pr = prev === "cohort" ? PREV0 : +prev;
    const ppv = se * pr / (se * pr + (1 - sp) * (1 - pr)), npv = sp * (1 - pr) / (sp * (1 - pr) + (1 - se) * pr);
    const acc = se * pr + sp * (1 - pr);
    el.querySelector("#c9thrv").textContent = (thr / 100).toFixed(2);
    el.querySelector("#c9se").textContent = f1(se);
    el.querySelector("#c9sp").textContent = f1(sp);
    el.querySelector("#c9ppv").textContent = f1(ppv);
    el.querySelector("#c9npv").textContent = f1(npv);
    el.querySelector("#c9acc").textContent = f1(acc);
    el.querySelector("#c9none").textContent = f1(1 - pr);
    const per = prev === "cohort"
      ? `이 코호트 2,400명 중 ${n0(TP + FP)}명을 고위험으로 분류하고, 그중 ${n0(TP)}명이 실제로 입원했습니다(입원한 ${n0(N1)}명 중 ${n0(N1 - TP)}명은 놓침).`
      : `입원 비율이 ${f1(pr)}인 환자 1,000명이라면 ${n0(1000 * (se * pr + (1 - sp) * (1 - pr)))}명을 고위험으로 분류하고, 그중 ${n0(1000 * se * pr)}명이 실제로 입원합니다.`;
    el.querySelector("#c9note").textContent = per + (acc < 1 - pr ? " 지금 임계값의 정확도는 아무도 입원하지 않는다고 예측할 때보다 낮습니다." : "");
    // chart: mirrored histogram of predicted risk, 0.02 bins, % within each group
    const W = 640, Hh = 300, L = 56, R = 16, T = 14, B = 50, xmax = 0.8, ymax = 12;
    const sx = x => L + x / xmax * (W - L - R), mid = (Hh - B + T) / 2, sy = v => mid - v / ymax * (mid - T);
    let s = "";
    for (const v of [-10, -5, 0, 5, 10]) s += `<line x1="${L}" y1="${sy(v)}" x2="${W - R}" y2="${sy(v)}" class="grid"/><text x="${L - 8}" y="${sy(v) + 4}" text-anchor="end" class="tick">${Math.abs(v)}</text>`;
    for (let k = 0; k < 40; k++) {
      const a = C1[2 * k] + C1[2 * k + 1], b = C0[2 * k] + C0[2 * k + 1];
      const x0 = sx(k * 0.02) + 1, w = sx(0.02) - sx(0) - 2, on = 2 * k >= thr;
      if (a) s += `<rect x="${x0}" y="${sy(a / N1 * 100)}" width="${w}" height="${sy(0) - sy(a / N1 * 100)}" class="f2" opacity="${on ? 1 : 0.35}"/>`;
      if (b) s += `<rect x="${x0}" y="${sy(0)}" width="${w}" height="${sy(-b / N0 * 100) - sy(0)}" class="f1" opacity="${on ? 1 : 0.35}"/>`;
    }
    s += `<line x1="${L}" y1="${sy(0)}" x2="${W - R}" y2="${sy(0)}" class="axis"/>`;
    for (const x of [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]) s += `<text x="${sx(x)}" y="${Hh - B + 18}" text-anchor="middle" class="tick">${x.toFixed(1)}</text>`;
    s += `<text x="${(L + W - R) / 2}" y="${Hh - 10}" text-anchor="middle" class="axlab">예측확률 (진하게 칠한 막대 = 고위험으로 분류)</text>`;
    s += `<line x1="${sx(thr / 100)}" y1="${T}" x2="${sx(thr / 100)}" y2="${Hh - B}" class="ref strongref" stroke-width="1.6" stroke-dasharray="5 4"/>`;
    s += `<text x="${W - R - 4}" y="${sy(9)}" text-anchor="end" class="lbl strong">입원한 환자</text>`;
    s += `<text x="${W - R - 4}" y="${sy(-9)}" text-anchor="end" class="lbl strong">입원하지 않은 환자</text>`;
    s += `<text x="${sx(thr / 100) + 6}" y="${T + 12}" class="lbl small">임계값 ${(thr / 100).toFixed(2)}</text>`;
    el.querySelector("#c9chart").innerHTML = `<svg viewBox="0 0 ${W} ${Hh}" class="viz" role="img" aria-label="입원 여부별 예측확률 분포와 임계값">${s}</svg>`;
  }
  el.querySelector("#c9thr").addEventListener("input", e => { thr = +e.target.value; draw(); });
  el.querySelectorAll(".seg button").forEach(b => b.addEventListener("click", () => {
    prev = b.dataset.p; el.querySelectorAll(".seg button").forEach(x => x.setAttribute("aria-pressed", x === b)); draw();
  }));
  draw();
};
